### ISSUE TITLE
ndpiReader creates malformed csv file

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/nDPI#820]
Hello, I am a new user of nDPI.

[My environment and ndpiReader version]
$ more /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
$ ../example/ndpiReader -v
../example/ndpiReader: option requires an argument -- 'v'
Welcome to nDPI 3.1.0-2050-2c2bb11

I tried to follow below Blog but I encountered the problem.
https://www.ntop.org/ndpi/how-to-use-ndpi-from-cli-to-analyse-network-traffic/

When I execute below command
$ sudo ../example/ndpiReader -i ./dos_slow.pcap -C dos_slow.csv

The second line of dos_slow.csv included all data....
$ ls -ltr
～snip～
-rw-r--r-- 1 root root  2860741 Dec 13 17:17 dos_slow.csv
demo@netvizura-demo:~/nDPI/tests$ wc dos_slow.csv
      1       2 2860741 dos_slow.csv

Does somebody know how to solve this?

**Comment by lucaderi** [comment]
This should have been solved by now

**Comment by a-czyrny** [comment]
The problem still exists when using the verbose packet print argument (tested with -v 1 & -v 2)
